### ISSUE TITLE
does not recognize align_corners = True in torch.grid sample

### ISSUE THREAD

**Issue by maorp** [DeformableFriends/NeuralTracking#1]
Hi. first thanks for the wonderful paper and implementation. i cant run it without removing all align_corners argumants. its not recognized by torch grid sample function. I installed on windows 10 according to the directions. it installed pytorch 1.2 on my machine. maybe it needs 1.4?

**Comment by AljazBozic** [comment]
Hi! True, we were using pytorch 1.4 on Linux. But according to https://pytorch.org/docs/stable/nn.functional.html#grid-sample, "the default behavior up to version 1.2.0 was align_corners = True". So when we tested it on Windows (also under pytorch 1.2), we just removed unsupported align_corners = True argument.

**Comment by AljazBozic** [comment]
Hi! True, we were always using pytorch 1.4. Unfortunately versions <=1.2 don't provide the parameters align_corners, and the default internal setting seems to not be consistent between interpolate and grid_sample methods, so we can only recommend to use pytorch 1.4. Hope that helps!

**Comment by maorp** [comment]
maybe the yml needs update or a windows version. with cudatoolkit=10.0 it auto installs pytorch 1.2 at least on windows. thanks again!

**Comment by pablopalafox** [comment]
Hi @maorp, you can also have a look at this issue https://github.com/sniklaus/pytorch-pwc/issues/33, at the [repo](https://github.com/sniklaus/pytorch-pwc) from which we took the pwcnet implementation in pytorch. In that issue, @sniklaus refers to pytorch/pytorch#23923.

**Comment by pablopalafox** [comment]
> maybe the yml needs update or a windows version. with cudatoolkit=10.0 it auto installs pytorch 1.2 at least on windows. thanks again!

good point, could you try again with the latest commit?

**Comment by pablopalafox** [comment]
hey @maorp, I guess we can close the issue for now. Please feel free to open it up again if things are not working.
