### ISSUE TITLE
Error: python example_viz.py

### ISSUE THREAD

**Issue by joos2010kj** [DeformableFriends/NeuralTracking#7]
Hello,

Thanks for the nice paper!

I wanted to reproduce the code after reading it, but I am having difficulties running it.  Could you look into this issue, please?

OS: Windows 10
Setup Approach: Local
Installation Response: 

> (nnrt) C:\Users\X\Desktop\NeuralTracking\csrc>python setup.py install
> No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1'
> running install
> running bdist_egg
> running egg_info
> writing NeuralNRT.egg-info\PKG-INFO
> writing dependency_links to NeuralNRT.egg-info\dependency_links.txt
> writing top-level names to NeuralNRT.egg-info\top_level.txt
> reading manifest file 'NeuralNRT.egg-info\SOURCES.txt'
> writing manifest file 'NeuralNRT.egg-info\SOURCES.txt'
> installing library code to build\bdist.win-amd64\egg
> running install_lib
> running build_ext
> C:\Users\X\anaconda3\envs\nnrt\lib\site-packages\torch\utils\cpp_extension.py:209: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
>   warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
> creating build\bdist.win-amd64\egg
> creating build\bdist.win-amd64\egg\NeuralNRT
> copying build\lib.win-amd64-3.7\NeuralNRT\_C.cp37-win_amd64.pyd -> build\bdist.win-amd64\egg\NeuralNRT
> creating stub loader for NeuralNRT\_C.cp37-win_amd64.pyd
> byte-compiling build\bdist.win-amd64\egg\NeuralNRT\_C.py to _C.cpython-37.pyc
> creating build\bdist.win-amd64\egg\EGG-INFO
> copying NeuralNRT.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
> copying NeuralNRT.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
> copying NeuralNRT.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
> copying NeuralNRT.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
> writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
> zip_safe flag not set; analyzing archive contents...
> NeuralNRT.__pycache__._C.cpython-37: module references __file__
> creating 'dist\NeuralNRT-1.0-py3.7-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
> removing 'build\bdist.win-amd64\egg' (and everything under it)
> Processing NeuralNRT-1.0-py3.7-win-amd64.egg
> removing 'c:\users\X\anaconda3\envs\nnrt\lib\site-packages\NeuralNRT-1.0-py3.7-win-amd64.egg' (and everything under it)
> creating c:\users\X\anaconda3\envs\nnrt\lib\site-packages\NeuralNRT-1.0-py3.7-win-amd64.egg
> Extracting NeuralNRT-1.0-py3.7-win-amd64.egg to c:\users\X\anaconda3\envs\nnrt\lib\site-packages
> NeuralNRT 1.0 is already the active version in easy-install.pth
> 
> Installed c:\users\X\anaconda3\envs\nnrt\lib\site-packages\neuralnrt-1.0-py3.7-win-amd64.egg
> Processing dependencies for NeuralNRT==1.0
> Finished processing dependencies for NeuralNRT==1.0

python example_viz.py Response:
> (nnrt) C:\Users\X\Desktop\NeuralTracking>python example_viz.py
> Traceback (most recent call last):
>   File "example_viz.py", line 8, in <module>
>     from model.model import DeformNet
>   File "C:\Users\X\Desktop\NeuralTracking\model\model.py", line 7, in <module>
>     import torchvision.models as models
>   File "C:\Users\X\anaconda3\envs\nnrt\lib\site-packages\torchvision\__init__.py", line 1, in <module>
>     from torchvision import models
>   File "C:\Users\X\anaconda3\envs\nnrt\lib\site-packages\torchvision\models\__init__.py", line 11, in <module>
>     from . import detection
>   File "C:\Users\X\anaconda3\envs\nnrt\lib\site-packages\torchvision\models\detection\__init__.py", line 1, in <module>
>     from .faster_rcnn import *
>   File "C:\Users\X\anaconda3\envs\nnrt\lib\site-packages\torchvision\models\detection\faster_rcnn.py", line 7, in <module>
>     from torchvision.ops import misc as misc_nn_ops
>   File "C:\Users\X\anaconda3\envs\nnrt\lib\site-packages\torchvision\ops\__init__.py", line 1, in <module>
>     from .boxes import nms, box_iou
>   File "C:\Users\X\anaconda3\envs\nnrt\lib\site-packages\torchvision\ops\boxes.py", line 2, in <module>
>     from torchvision import _C
> ImportError: DLL load failed: The specified module could not be found.
> 
> (nnrt) C:\Users\X\Desktop\NeuralTracking>

Thank you.

**Comment by pablopalafox** [comment]
Hi @joos2010kj! Thanks a lot for the interest in our paper :)

Unfortunately we never tested the code on Windows, only on Ubuntu 20.04. In any case, I looked it up and found [this issue](https://stackoverflow.com/questions/20201868/importerror-dll-load-failed-the-specified-module-could-not-be-found). Maybe you can try it out and let us know.

**Comment by joos2010kj** [comment]
Instead of Windows, I tested with Linux dualboot and it worked.

OS: Ubuntu 20.04
GPU: 2070S
Nvidia Driver Version: 450
Approach: Docker
